(()=>{'use strict';
const englishData={
'2a':'Euthyphro is surprised to find Socrates away from the Lyceum and instead at the Stoa Basileios. Socrates explains that he is there because a formal accusation has been made against him.',
'2b':'Euthyphro asks who has brought the accusation. Socrates identifies Meletus, describing him as a young and largely unfamiliar man from Pitthus.',
'2c':'Socrates describes Meletus’ charge as one concerned with the corruption of the young and presents the accusation with characteristic irony, linking it to civic responsibility and education.',
'3':'The accusation turns explicitly toward religion: Socrates is charged with introducing new divine things and failing to recognise the traditional gods. Euthyphro responds by comparing Socrates’ experience with his own claims to unusual religious knowledge.',
'4':'Euthyphro explains that he is prosecuting his own father over a death. The conversation increasingly joins legal procedure, kinship, religious obligation and claims to expertise about piety.',
'5a':'Euthyphro defends his prosecution by appealing to divine precedent, including Zeus and the punishment of fathers by sons. Socrates presses him on whether stories about conflict among the gods should be accepted.'};
const evidence=[
{id:'stoa',title:'Stoa Basileios',badge:'EXPLICIT — IN THE TEXT',text:'Plato explicitly locates Socrates around the Basileus’ stoa. Archaeology independently anchors the Royal Stoa at the northwest corner of the Agora.'},
{id:'herms',title:'Herm bases and “The Herms”',badge:'IMPLICIT — CONTEXTUAL EVIDENCE',text:'Excavated herm bases and ancient testimony support a substantial hermic presence around the northwest Agora. The complete arrangement in 399 BCE is not recoverable.'},
{id:'zeus',title:'Stoa of Zeus Eleutherios',badge:'IMPLICIT — CONTEXTUAL EVIDENCE',text:'The neighbouring stoa formed part of the immediate recoverable built environment although Plato does not name it in Euthyphro 2a–5a.'},
{id:'approach',title:'Panathenaic approach',badge:'IMPLICIT — CONTEXTUAL EVIDENCE',text:'The Royal Stoa stood at the northwest entrance to the Agora where major routes converged and the Panathenaic Way entered the square.'},
{id:'shrine',title:'Classical shrine and votive material',badge:'IMPLICIT — CONTEXTUAL EVIDENCE',text:'Religious material excavated east of the Royal Stoa supplies an independently recoverable religious dimension to the setting.'},
{id:'eridanos',title:'Eridanos channel',badge:'IMPLICIT — CONTEXTUAL EVIDENCE',text:'The Classical channel can be spatially reconstructed beside the Royal Stoa and approach. Its sensory prominence remains unknown.'},
{id:'basileus',title:'King Archon and legal-religious procedure',badge:'IMPLICIT — CONTEXTUAL EVIDENCE',text:'The office and location connect the opening scene to a recoverable institutional context in which legal and religious responsibilities overlap.'},
{id:'opening',title:'Situated opening',badge:'IMPLICIT — CONTEXTUAL EVIDENCE',text:'Across 2a–5a the opening links piety, prosecution, office, place and material environment before sustained definitional inquiry begins. Its significance remains interpretative.'}
];
let currentSec='2a',currentLang='greek',mapObj=null,osm=null,ancient=null,markers=[];
function openTab(name){document.querySelectorAll('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));window.scrollTo({top:0,behavior:'instant'});if(name==='spatial')setTimeout(()=>{initMap();if(mapObj)mapObj.invalidateSize()},60)}
function updateText(){const d=sectionData[currentSec];document.querySelector('#reviewText').textContent=currentLang==='greek'?d.g:englishData[currentSec];document.querySelector('#explicitTitle').textContent=d.t;document.querySelector('#explicitBody').textContent=d.b;document.querySelectorAll('[data-sec]').forEach(b=>b.classList.toggle('active',b.dataset.sec===currentSec));document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===currentLang));document.querySelector('#reviewText').classList.toggle('english-mode',currentLang==='english')}
function buildEvidence(){document.querySelector('#evidenceGrid').innerHTML=evidence.map(e=>`<article class="evidence-card"><span class="evidence-badge">${e.badge}</span><h3>${e.title}</h3><p>${e.text}</p><a href="references.html#${e.id}" target="_blank" rel="noopener">Open references & further research ↗</a></article>`).join('')}
function markerIcon(type,label){return L.divIcon({className:'',html:`<div class="marker-shape ${type}"><span>${label}</span></div>`,iconSize:[24,24],iconAnchor:[12,12]})}
function initMap(){if(mapObj||!window.L)return;const centre=[37.97610,23.72243],bounds=[[37.97275,23.72015],[37.97755,23.72525]];mapObj=L.map('reviewMap',{minZoom:15,maxZoom:21,zoomSnap:.25}).setView(centre,19);osm=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:21,attribution:'© OpenStreetMap contributors'}).addTo(mapObj);ancient=L.imageOverlay('../preview-v2/ancient-agora-map.svg',bounds,{opacity:1,interactive:false});const data=[
{name:'Stoa Basileios',lat:37.976123,lng:23.722336,type:'places',shape:'place',short:'S',evidence:'Explicit in Euthyphro 2a; archaeologically identified.',confidence:'High location confidence; exact dramatic standing point unknown.'},
{name:'Stoa of Zeus Eleutherios',lat:37.975843,lng:23.722163,type:'places',shape:'place',short:'Z',evidence:'Attested neighbouring civic/religious architecture.',confidence:'High archaeological location confidence.'},
{name:'Herm bases / “The Herms”',lat:37.976205,lng:23.722392,type:'material',shape:'material',short:'H',evidence:'Materially attested herm bases and wider concentration.',confidence:'Findspots attested; complete 399 BCE arrangement incomplete.'},
{name:'Classical shrine & votive material',lat:37.97616,lng:23.72263,type:'material',shape:'material',short:'R',evidence:'Excavated religious material east of the Royal Stoa.',confidence:'Excavation context attested; display point generalised.'},
{name:'Panathenaic Way / northwest approach',lat:37.97634,lng:23.72268,type:'movement',shape:'movement',short:'P',evidence:'Topographically attested approach into the Agora.',confidence:'Route relationship strong; exact travelled surface reconstructed.'},
{name:'Eridanos channel',lat:37.97642,lng:23.72230,type:'movement',shape:'movement',short:'E',evidence:'Classical channel recoverable from archaeology.',confidence:'Course recoverable; sensory salience unknown.'},
{name:'Socrates & Euthyphro encounter zone',lat:37.97610,lng:23.72243,type:'people',shape:'event',short:'2a',evidence:'Analytical anchor for the dramatic encounter.',confidence:'Vicinity only; exact standing point unknown.'}
];markers=data.map(d=>{const m=L.marker([d.lat,d.lng],{icon:markerIcon(d.shape,d.short)}).addTo(mapObj);m.review=d;m.bindTooltip(d.name);m.on('click',()=>showFeature(d));return m});
function setMode(mode){[osm,ancient].forEach(l=>{if(l&&mapObj.hasLayer(l))mapObj.removeLayer(l)});if(mode==='modern'){osm.addTo(mapObj);mapObj.setView(centre,19,{animate:false})}else if(mode==='historic'){ancient.setOpacity(1).addTo(mapObj);mapObj.fitBounds(bounds,{padding:[18,18],animate:false})}else{osm.addTo(mapObj);ancient.setOpacity(.54).addTo(mapObj);mapObj.fitBounds(bounds,{padding:[18,18],animate:false})}}
document.querySelectorAll('[data-mapmode]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-mapmode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');setMode(b.dataset.mapmode)}));document.querySelectorAll('[data-layer-filter]').forEach(c=>c.addEventListener('change',()=>{const active=new Set([...document.querySelectorAll('[data-layer-filter]:checked')].map(x=>x.dataset.layerFilter));markers.forEach(m=>{const show=active.has(m.review.type);if(show&&!mapObj.hasLayer(m))m.addTo(mapObj);if(!show&&mapObj.hasLayer(m))mapObj.removeLayer(m)})}))}
function showFeature(d){document.querySelector('#featureRecord').innerHTML=`<div class="eyebrow">Feature record</div><h3>${d.name}</h3><p>${d.evidence}</p><dl><dt>Evidence type</dt><dd>${d.type==='places'?'Place / institution':d.type==='material'?'Material culture':d.type==='movement'?'Movement / route':'Person / event'}</dd><dt>Confidence</dt><dd>${d.confidence}</dd></dl>`}
const pieceCopy={text:'The surviving text supplies the named place, the legal situation, the two speakers and the emerging questions of piety, prosecution, kinship and divine precedent.',material:'Add the recoverable material setting: the Stoa Basileios, neighbouring civic and religious architecture, herm bases, approach routes, votive material and infrastructure. These do not alter the Greek; they alter the contextual field around it.',memory:'Add the wider social narrative: cultural representations of Socrates, the institutional associations of the Basileus, the civic memory surrounding the herms, and other associations that may have been available to some receivers.',reader:'Add the modern reader. We bring our own translations, educational traditions, philosophical canon, cultural image of Socrates and expectations about religion, law and philosophy. Recovery of ancient context does not erase modern reception; it makes it more visible.'};
function initJigsaw(){document.querySelector('#jigsawText').textContent=sectionData['2a'].g;document.querySelector('#jigsawLayer').textContent=pieceCopy.text;document.querySelectorAll('[data-piece]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-piece]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#jigsawLayer').textContent=pieceCopy[b.dataset.piece]}))}
function init(){buildEvidence();updateText();initJigsaw();document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.tab)));document.querySelectorAll('[data-sec]').forEach(b=>b.addEventListener('click',()=>{currentSec=b.dataset.sec;updateText()}));document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{currentLang=b.dataset.lang;updateText()}));document.querySelectorAll('.layer-bar button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.layer-bar button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('#map').dataset.layer=btn.dataset.layer}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();