(()=>{'use strict';
const views={
 approach:{label:'Panathenaic approach · arrival and movement',src:'../preview-v2/images/reconstruction_approach.jpg',w:1000,h:520,features:[['hermA',121,235,1],['hermB',553,355,2],['river',230,460,3],['route',354,367,4],['stoa',765,156,5],['civicEdge',992,305,6]]},
 panorama:{label:'Stoa & immediate environment',src:'../preview-v2/images/reconstruction_panorama_scene.jpg',w:1648,h:587,features:[['hermA',105,266,1],['hermB',699,343,2],['river',1131,523,3],['route',1198,409,4],['acropolis',1088,112,5]]},
 agora:{label:'Agora-facing civic landscape',src:'../preview-v2/images/reconstruction_agora.png',w:1648,h:920,features:[['stoa',147,331,1],['zeus',676,382,2],['agora',1011,438,3],['civicEdge',1595,476,4],['temple',1367,365,5],['acropolis',1320,121,6]]}
};
const evidence={
 stoa:{title:'Stoa Basileios / stoa environment',status:'attested',statusLabel:'Explicit · Attested place',text:'Plato explicitly places Socrates around the Basileus’ stoa. Archaeology securely anchors the Royal Stoa in the northwest Agora; the rendered architecture remains reconstructed.',relation:'Explicit in Euthyphro 2a',confidence:'High location confidence; exact standing point and rendered appearance remain reconstructed.'},
 hermA:{title:'Herm / hermic presence',status:'attested',statusLabel:'Materially attested · Implicit',text:'Excavated herm bases and ancient testimony support a substantial hermic presence around the northwest Agora. A rendered individual herm is illustrative rather than a claim about one exact object at one exact point.',relation:'Not enumerated in Euthyphro 2a–5a',confidence:'Hermic concentration attested; exact 399 BCE arrangement incomplete.'},
 hermB:{title:'Herm / civic material culture',status:'attested',statusLabel:'Materially attested · Implicit',text:'The concentration of herms matters because it adds material information to the dramatic environment that Plato does not need to enumerate in the surviving passage.',relation:'Implicit material context',confidence:'Material presence supported; individual placement reconstructed.'},
 route:{title:'Panathenaic approach / movement corridor',status:'reconstructed',statusLabel:'Topographical · Reconstructed',text:'The Royal Stoa marked the northwest entrance where major routes converged and the Panathenaic Way entered the Agora. The movement relationship is recoverable; the exact travelled surface and momentary activity shown are reconstructed.',relation:'Implicit spatial context',confidence:'Route relationship strong; rendered surface illustrative.'},
 river:{title:'Eridanos channel',status:'reconstructed',statusLabel:'Reconstructed infrastructure',text:'The Classical channel can be reconstructed beside the Royal Stoa and approach. Its visual, acoustic or olfactory prominence to an individual remains unknown.',relation:'Implicit environmental context',confidence:'Course recoverable; sensory salience unknown.'},
 civicEdge:{title:'Civic edge / adjacent material environment',status:'possible',statusLabel:'Possible perceptual context',text:'This point represents the dense architectural and material edge around the encounter zone. The broader setting is historically recoverable, but what any one observer noticed cannot be universalised.',relation:'Implicit environmental context',confidence:'Setting recoverable; perceptual salience unknown.'},
 zeus:{title:'Stoa of Zeus Eleutherios',status:'attested',statusLabel:'Attested · Implicit',text:'The neighbouring Stoa of Zeus Eleutherios formed part of the immediate built environment beside the Royal Stoa even though Plato does not name it in the opening passage.',relation:'Implicit built context',confidence:'High archaeological location confidence; rendered appearance reconstructed.'},
 agora:{title:'Wider Agora civic space',status:'interpretative',statusLabel:'Interpretative synthesis',text:'Pulling outward from the encounter situates the dialogue within a broader civic landscape of movement, monuments and institutions. The interpretative significance of that density remains a proposition to test.',relation:'Interpretative context',confidence:'Composite visualisation; meaning remains open to testing.'},
 temple:{title:'Wider monumental landscape',status:'possible',statusLabel:'Possible wider orientation',text:'A wider view can help visitors understand that the encounter belongs to a monumental civic landscape, while any specific sightline or visual prominence must remain explicitly uncertain.',relation:'Possible wider orientation',confidence:'Rendered building form and prominence viewpoint-dependent.'},
 acropolis:{title:'Acropolis / wider city orientation',status:'possible',statusLabel:'Possible visual context',text:'The Acropolis provides city-scale orientation in the reconstruction. Exact visibility and prominence from a particular ancient standing point depend on topography, buildings and viewpoint reconstruction.',relation:'Possible wider orientation',confidence:'Visibility and prominence viewpoint-dependent.'}
};
let currentView='approach',currentMode='reconstruction';
const scene=document.querySelector('#scene'),img=document.querySelector('#sceneImage'),overlay=document.querySelector('#evidenceOverlay'),record=document.querySelector('#record'),viewName=document.querySelector('#viewName'),slider=document.querySelector('#recoverySlider'),recoveryLabel=document.querySelector('#recoveryLabel');
function resetRecord(){record.innerHTML='<div class="eyebrow">Evidence record</div><h2>Select a numbered feature</h2><p>The numbers already visible in the image are the clickable evidence points. Select one to inspect its evidence status, uncertainty and potential significance.</p>'}
function renderOverlay(){overlay.innerHTML='';const v=views[currentView];overlay.setAttribute('viewBox',`0 0 ${v.w} ${v.h}`);v.features.forEach(([id,x,y,num])=>{const d=evidence[id],g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class',`ir-hit ${d.status}`);g.dataset.id=id;g.dataset.kind=d.status;g.setAttribute('transform',`translate(${x} ${y})`);g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',`${num}. ${d.title}`);g.innerHTML='<circle class="hit-zone" r="28"></circle><circle class="focus-ring" r="24"></circle>';g.addEventListener('click',()=>selectFeature(id,g));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectFeature(id,g)}});overlay.appendChild(g)});applyMode();applyRecovery()}
function selectFeature(id,node){document.querySelectorAll('.ir-hit').forEach(n=>n.classList.remove('selected'));if(node)node.classList.add('selected');const d=evidence[id];record.innerHTML=`<div class="eyebrow">Evidence record · ${d.statusLabel}</div><h2>${d.title}</h2><p>${d.text}</p><div class="ir-meta"><div><span>Textual relation</span><strong>${d.relation}</strong></div><div><span>Uncertainty</span><strong>${d.confidence}</strong></div></div>`}
function setView(id){if(!views[id])return;currentView=id;document.querySelectorAll('#viewTabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));img.src=views[id].src;viewName.textContent=views[id].label;resetRecord();renderOverlay()}
function applyMode(){document.querySelectorAll('#modeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===currentMode));scene.dataset.mode=currentMode;document.querySelectorAll('.ir-hit').forEach(n=>{n.classList.remove('dimmed');if(currentMode==='implicit'){const d=evidence[n.dataset.id];if(d.relation.startsWith('Explicit'))n.classList.add('dimmed')}if(currentMode==='uncertainty'&&n.dataset.kind==='attested')n.classList.add('dimmed')});if(currentMode==='reconstruction')img.style.filter='none';else if(currentMode==='evidence')img.style.filter='saturate(.78) brightness(.88)';else if(currentMode==='implicit')img.style.filter='saturate(.72) brightness(.82)';else img.style.filter='grayscale(.3) brightness(.78)'}
function applyRecovery(){const val=Number(slider.value),nodes=[...document.querySelectorAll('.ir-hit')];recoveryLabel.textContent=`Recovered environment: ${val}%`;img.style.opacity=String(.3+.7*(val/100));const showCount=Math.round(nodes.length*(val/100));nodes.forEach((n,i)=>n.classList.toggle('hidden',i>=showCount));if(val===0){record.innerHTML='<div class="eyebrow">Text-only condition</div><h2>What remains?</h2><p>The contextual layer has been removed. The experiment asks what information disappears when the dramatic environment is reduced to the surviving textual reference to place.</p>'}}
document.querySelectorAll('#viewTabs button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
document.querySelectorAll('#modeTabs button').forEach(b=>b.addEventListener('click',()=>{currentMode=b.dataset.mode;applyMode()}));slider.addEventListener('input',applyRecovery);setView('approach')})();