(()=>{'use strict';
const views={
 approach:{label:'Panathenaic approach · arrival and movement',src:'../preview-v2/images/reconstruction_approach.jpg',features:[['hermA',12.1,45.2,1],['hermB',55.3,68.3,2],['river',23.0,88.5,3],['route',35.4,70.6,4],['stoa',76.5,30.0,5],['civicEdge',97.0,58.7,6]]},
 panorama:{label:'Stoa & immediate environment',src:'../preview-v2/images/reconstruction_panorama_scene.jpg',features:[['hermA',6.4,45.3,1],['hermB',42.4,58.4,2],['river',68.6,89.1,3],['route',72.7,69.7,4],['acropolis',66.0,19.1,5]]},
 agora:{label:'Agora-facing civic landscape',src:'../preview-v2/images/reconstruction_agora.png',features:[['stoa',8.9,36.0,1],['zeus',41.0,41.5,2],['agora',61.3,47.6,3],['civicEdge',96.0,51.7,4],['temple',83.0,39.7,5],['acropolis',80.1,13.2,6]]}
};
const evidence={
 stoa:{title:'Stoa Basileios / stoa environment',status:'attested',statusLabel:'Explicit · Attested place',text:'Plato explicitly places Socrates around the Basileus’ stoa. Archaeology securely anchors the Royal Stoa in the northwest Agora; the rendered architecture remains reconstructed.',relation:'Explicit in Euthyphro 2a',confidence:'High location confidence; exact standing point and rendered appearance remain reconstructed.'},
 hermA:{title:'Herm / hermic presence',status:'attested',statusLabel:'Materially attested · Implicit',text:'Excavated herm bases and ancient testimony support a substantial hermic presence around the northwest Agora. A rendered individual herm is illustrative rather than a claim about one exact object at one exact point.',relation:'Not enumerated in Euthyphro 2a–5a',confidence:'Hermic concentration attested; exact 399 BCE arrangement incomplete.'},
 hermB:{title:'Herm / civic material culture',status:'attested',statusLabel:'Materially attested · Implicit',text:'The concentration of herms matters because it adds material information to the dramatic environment that Plato does not need to enumerate in the surviving passage.',relation:'Implicit material context',confidence:'Material presence supported; individual placement reconstructed.'},
 route:{title:'Panathenaic approach / movement corridor',status:'reconstructed',statusLabel:'Topographical · Reconstructed',text:'The Royal Stoa marked the northwest entrance where major routes converged and the Panathenaic Way entered the Agora. The movement relationship is recoverable; the exact travelled surface and momentary activity shown are reconstructed.',relation:'Implicit spatial context',confidence:'Route relationship strong; rendered surface illustrative.'},
 river:{title:'Eridanos channel',status:'reconstructed',statusLabel:'Reconstructed infrastructure',text:'The Classical channel can be reconstructed beside the Royal Stoa and approach. Its visual, acoustic or olfactory prominence to an individual remains unknown.',relation:'Implicit environmental context',confidence:'Course recoverable; sensory salience unknown.'},
 civicEdge:{title:'Civic edge / adjacent material environment',status:'possible',statusLabel:'Possible perceptual context',text:'This point represents the dense architectural and material edge around the encounter zone. The broader setting is historically recoverable, but what any one observer noticed cannot be universalised.',relation:'Implicit environmental context',confidence:'Setting recoverable; perceptual salience unknown.'},
 zeus:{title:'Stoa of Zeus Eleutherios',status:'attested',statusLabel:'Attested · Implicit',text:'The neighbouring Stoa of Zeus Eleutherios formed part of the immediate built environment beside the Royal Stoa even though Plato does not name it in the opening passage.',relation:'Implicit built context',confidence:'High archaeological location confidence; rendered appearance reconstructed.'},
 agora:{title:'Wider Agora civic space',status:'interpretative',statusLabel:'Interpretative synthesis',text:'Pulling outward from the encounter situates the dialogue within a broader civic landscape of movement, monuments and institutions. The interpretative significance of that density remains a proposition to test.',relation:'Interpretative context',confidence:'Composite visualisation; meaning remains open to testing.'},
 temple:{title:'Wider monumental landscape',status:'possible',statusLabel:'Possible wider orientation',text:'A wider view can help visitors understand that the encounter belongs to a monumental civic landscape, while any specific sightline or visual prominence must remain explicitly uncertain.',relation:'Possible wider orientation',confidence:'Rendered building form and prominence viewpoint-dependent.'},
 acropolis:{title:'Acropolis / wider city orientation',status:'possible',statusLabel:'Possible visual context',text:'The Acropolis provides city-scale orientation in the reconstruction. Exact visibility and prominence from a particular ancient standing point depend on topography, buildings and viewpoint reconstruction.',relation:'Possible wider orientation',confidence:'Visibility and prominence viewpoint-dependent.'}
};
let currentView='approach';
const img=document.querySelector('#sceneImage'),overlay=document.querySelector('#evidenceOverlay'),record=document.querySelector('#record'),viewName=document.querySelector('#viewName');
function resetRecord(){record.innerHTML='<div class="eyebrow">Evidence record</div><h2>Select a numbered feature</h2><p>Select a numbered point on the reconstruction to inspect its evidence status, uncertainty and potential significance.</p>'}
function renderOverlay(){overlay.innerHTML='';views[currentView].features.forEach(([id,x,y,num])=>{const d=evidence[id];const b=document.createElement('button');b.type='button';b.className=`ir-hotspot ${d.status}`;b.style.left=`${x}%`;b.style.top=`${y}%`;b.dataset.id=id;b.setAttribute('aria-label',`${num}. ${d.title}`);b.innerHTML=`<span class="sr-only">${num}. ${d.title}</span>`;b.addEventListener('click',()=>selectFeature(id,b));overlay.appendChild(b)})}
function selectFeature(id,node){document.querySelectorAll('.ir-hotspot').forEach(n=>n.classList.remove('selected'));if(node)node.classList.add('selected');const d=evidence[id];record.innerHTML=`<div class="eyebrow">Evidence record · ${d.statusLabel}</div><h2>${d.title}</h2><p>${d.text}</p><div class="ir-meta"><div><span>Textual relation</span><strong>${d.relation}</strong></div><div><span>Uncertainty</span><strong>${d.confidence}</strong></div></div>`}
function setView(id){if(!views[id])return;currentView=id;document.querySelectorAll('#viewTabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));img.onload=()=>renderOverlay();img.src=views[id].src;viewName.textContent=views[id].label;resetRecord();if(img.complete)renderOverlay()}
document.querySelectorAll('#viewTabs button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
setView('approach');
})();